# Group4: MseI+CviQI+TA+SeqB 配置文件
# 样本: MME-3 (2个文件)

S1_config:
  patterns: "ATGTCGGAGTTCTTAGGCGCTGGTTGCGTTGAGAACTCCGACT"  # SeqB连接序列
  description: "Group4_MseI_CviQI_TA_SeqB_Linker_Separation"
  input_pattern: "*.fq.gz"
  lines_to_process: 1000000000
  jobs: 2
  output_dir: "Group4_S1_Linker_Separated"

S2_config:
  separator1: "TAATGTCGGAGTTCTTAGGCGCTGGTTGCGTTGAGAACTCCGACTTA"  # TA酶切位点+SeqB连接序列
  separator2: "AGATCGGAAGA"  # 通用adapter序列
  min_length: 5
  output_dir: "Group4_S2_Enzyme_Split"

HiC_config:
  input_dir: "Group4_HiC_Input"
  project_name: "Group4_MseI_CviQI_TA_SeqB_HiC"
  config_type: 1
  modules: "2,3"  # 默认跳过trim模块
  cpu_count: 10
  conda_env: "hicpro3"
  script_type: "new"  # 'new'=新版本脚本(默认), 'old'=旧版本脚本

workflow_control:
  skip_s1: false
  skip_s2: false
  skip_hic: false

advanced_config:
  generate_report: true
  input_data_dir: "/data1/maolp/Biosoft/Myscript/sequence-processing-toolkit/data/fastq/Allfq/ByGroups/Group4_MseI_CviQI_TA_SeqB" 